### ISSUE TITLE
Как с этим работать

### ISSUE THREAD

**Issue by gademgold** [NotMyWing/Omnifactory-ru_RU#4]
Пожалуйста создайте в описании инструкции по установки данной модификации !Я просто пробывал установить в сборку это дополнение ,а в итоге ничего не произошло(перетащил все из src  в папку, где находилась сборка).

**Comment by NotMyWing** [comment]
К сожалению, перевод ещё не завершён даже на десять процентов ввиду нехватки времени для работы над ним. Но я надеюсь, что он завершится к моменту выхода версии 1.2.3.

**Comment by NotMyWing** [comment]
Все инструкции, архивы и остальное будут добавлены по мере продвижения работы. Пока что переведена лишь пара квестов.

**Comment by gademgold** [comment]
Спасибо
